services:
  postgres:
    image: postgres:14.1-alpine
    container_name: assistente-postgres
    hostname: assistente-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 1000:5432
    volumes: 
      - assistente-postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: assistente-pgadmin
    hostname: assistente-pgadmin
    restart: unless-stopped
    ports:
      - 1001:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@assistente.dev
      - PGADMIN_DEFAULT_PASSWORD=admin

  qdrant:
    image: qdrant/qdrant
    container_name: assistente-qdrant
    hostname: qdrant
    restart: unless-stopped
    ports:
      - 1002:6333
      - 1003:6334
    volumes:
      - assistente-qdrant:/qdrant/storage

  rabbitmq:
    image: rabbitmq:3.7.7-management
    container_name: assistente-rabbitmq
    hostname: assistente-rabbitmq
    restart: unless-stopped
    ports:
      - 1004:5672
      - 1005:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
    volumes:
      - assistente-rabbitmq:/var/lib/rabbitmq

  seq:
    image: datalust/seq:latest
    container_name: assistente-seq
    hostname: assistente-seq
    restart: unless-stopped
    ports:
      - 1006:80
      - 1007:5341
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - assistente-seq:/data

  ui:
    image: armatysme/assistente-ui:latest
    container_name: ui
    hostname: assistente-ui
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 1008:80
    # TODO: Mount appsettings.json
    
    environment:
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}
      - OpenAI__ApiKey=${OpenAI_ApiKey}
      - Qdrant__Host=${Qdrant_Host}
      - Rabbit__Name=${Rabbit_Name}
      - Rabbit__Url=${Rabbit_Url}
      - InternalApi__Url=${InternalApi_Url}
  
  db-upgrade:
    image: armatysme/assistente-db-upgrade:latest
    container_name: db-upgrade
    depends_on:
      - postgres
    environment:
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}

  api:
    image: armatysme/assistente-api:latest
    container_name: api
    hostname: assistente-api
    restart: unless-stopped
    depends_on:
      - worker-sync
    ports:
      - 1009:8080
    environment:
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}
      - OpenAI__ApiKey=${OpenAI_ApiKey}
      - Qdrant__Host=${Qdrant_Host}
      - Rabbit__Name=${Rabbit_Name}
      - Rabbit__Url=${Rabbit_Url}
      - InternalApi__Url=${InternalApi_Url}

  worker-sync:
    image: armatysme/assistente-worker-sync:latest
    container_name: worker-sync
    hostname: assistente-worker-sync
    restart: unless-stopped
    depends_on:
      - postgres
      - rabbitmq
      - qdrant
    ports:
      - 1010:8080
    environment:
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}
      - OpenAI__ApiKey=${OpenAI_ApiKey}
      - Qdrant__Host=${Qdrant_Host}
      - Rabbit__Name=${Rabbit_Name}
      - Rabbit__Url=${Rabbit_Url}
      - InternalApi__Url=${InternalApi_Url}

volumes:
  assistente-postgres:
    driver: local
  assistente-qdrant:
    driver: local
  assistente-rabbitmq:
    driver: local
  assistente-seq:
    driver: local