version: "3"

services:
  ui:
    container_name: ui
    restart: unless-stopped
    build:
      args:
        - ASSEMBLY_NAME=ASSISTENTE.UI
        - PROJECT_PATH=ASSISTENTE.UI
      context: .
      dockerfile: Docker/Blazor/Dockerfile
    ports:
      - 5291:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    networks:
      - localhost-network
  
  api:
    container_name: api
    hostname: assistente-api
    restart: unless-stopped
    build:
      args:
        - ASSEMBLY_NAME=ASSISTENTE.API
        - PROJECT_PATH=ASSISTENTE.API
      context: .
      dockerfile: Docker/API/Dockerfile
    ports:
      - 5249:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}
      - OpenAI__ApiKey=${OpenAI_ApiKey}
      - Qdrant__Host=${Qdrant_Host}
      - Rabbit__Name=${Rabbit_Name}
      - Rabbit__Url=${Rabbit_Url}
      - InternalApi__Url=${InternalApi_Url}
      - KnowledgePaths__MarkdownNotes=${KnowledgePaths_MarkdownNotes}
      - KnowledgePaths__Repositories=${KnowledgePaths_Repositories}
    networks:
      - localhost-network

  worker-sync:
    container_name: worker-sync
    hostname: assistente-worker-sync
    restart: unless-stopped
    build:
      args:
        - ASSEMBLY_NAME=ASSISTENTE.Worker.Sync
        - PROJECT_PATH=ASSISTENTE.Worker.Sync
      context: .
      dockerfile: Docker/API/Dockerfile
    ports:
      - 5133:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__AssistenteDatabase=${ConnectionStrings_AssistenteDatabase}
      - OpenAI__ApiKey=${OpenAI_ApiKey}
      - Qdrant__Host=${Qdrant_Host}
      - Rabbit__Name=${Rabbit_Name}
      - Rabbit__Url=${Rabbit_Url}
      - InternalApi__Url=${InternalApi_Url}
      - KnowledgePaths__MarkdownNotes=${KnowledgePaths_MarkdownNotes}
      - KnowledgePaths__Repositories=${KnowledgePaths_Repositories}
    networks:
      - localhost-network
        
networks:
  localhost-network:
    external: true